name: Show Current Date
on:
  pull_request:
    types: [opened, synchronize]
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  print-date: 
    runs-on: ubuntu-latest

    steps:
    - name: Print current date
      run: echo "Current date ant time is:$(date)"

